# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: ja

pipeline:
- name: SpacyNLP
  model: "ja_core_news_md"
### convert zenkaku eisu to hankaku eisu
- name: "customComponents.zenkakuToHankakuEisu"
- name: SpacyTokenizer
  "intent_tokenization_flag": False
  "intent_split_symbol": "_"
  "token_pattern": None
- name: SpacyFeaturizer
  "pooling": "mean"
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 5
- name: DIETClassifier
  epochs: 200
### when you have synonyms, you can use the following
- name: EntitySynonymMapper
- name: DucklingHTTPExtractor
  url: "http://localhost:8000"
  dimensions: ["number"]
  timeout: 3
- name: ResponseSelector
  epochs: 200
  retrieval_intent: greet
#- name: FallbackClassifier
#  threshold: 0.3
#  ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#   - name: RulePolicy
